<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>功夫小子登录器</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../dist/launcher-components/OnlineBridge.exe" LogicalName="OnlineBridge.exe" />
    <EmbeddedResource Include="../../dist/launcher-components/LoginSkin.dll" LogicalName="LoginSkin.dll" />
    <EmbeddedResource Include="../../dist/launcher-components/LoginSkinHost.exe" LogicalName="LoginSkinHost.exe" />
  </ItemGroup>
</Project>
