-- Schema snapshot from internal/persistence/store.go and admin.go (2026-09-20).
-- Select an existing empty database first; not an upgrade/migration script.
-- Dependency order preserved; no accounts, credentials, or game resources.

CREATE TABLE IF NOT EXISTS honour_rules(id TINYINT UNSIGNED PRIMARY KEY,revision BIGINT UNSIGNED NOT NULL,rules MEDIUMBLOB NOT NULL) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS honour_rules_audit(revision BIGINT UNSIGNED PRIMARY KEY,before_data MEDIUMBLOB NOT NULL,after_data MEDIUMBLOB NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS battle_reward_rules(id TINYINT UNSIGNED PRIMARY KEY,revision BIGINT UNSIGNED NOT NULL,rules MEDIUMBLOB NOT NULL) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS training_rules(id TINYINT UNSIGNED PRIMARY KEY,revision BIGINT UNSIGNED NOT NULL,rules MEDIUMBLOB NOT NULL) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS weapon_rules(id TINYINT UNSIGNED PRIMARY KEY,revision BIGINT UNSIGNED NOT NULL,rules MEDIUMBLOB NOT NULL) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS weapon_rules_audit(revision BIGINT UNSIGNED PRIMARY KEY,before_data MEDIUMBLOB NOT NULL,after_data MEDIUMBLOB NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS talisman_rules(id TINYINT UNSIGNED PRIMARY KEY,revision BIGINT UNSIGNED NOT NULL,rules MEDIUMBLOB NOT NULL) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS talisman_rules_audit(revision BIGINT UNSIGNED PRIMARY KEY,before_data MEDIUMBLOB NOT NULL,after_data MEDIUMBLOB NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS task_rules(id TINYINT UNSIGNED PRIMARY KEY,revision BIGINT UNSIGNED NOT NULL,rules MEDIUMBLOB NOT NULL) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS title_rules(id TINYINT UNSIGNED PRIMARY KEY,revision BIGINT UNSIGNED NOT NULL,rules MEDIUMBLOB NOT NULL) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS title_rules_audit(revision BIGINT UNSIGNED PRIMARY KEY,before_data MEDIUMBLOB NOT NULL,after_data MEDIUMBLOB NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS task_rules_audit(revision BIGINT UNSIGNED PRIMARY KEY,before_data MEDIUMBLOB NOT NULL,after_data MEDIUMBLOB NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS training_rules_audit(revision BIGINT UNSIGNED PRIMARY KEY,before_data MEDIUMBLOB NOT NULL,after_data MEDIUMBLOB NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS stage_access(id TINYINT UNSIGNED PRIMARY KEY,revision BIGINT UNSIGNED NOT NULL,rules MEDIUMBLOB NOT NULL) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS stage_player_unlock_audit(uid BIGINT UNSIGNED NOT NULL,client_hash CHAR(64) CHARACTER SET ascii NOT NULL,revision BIGINT UNSIGNED NOT NULL,before_data MEDIUMBLOB NOT NULL,after_data MEDIUMBLOB NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(uid,client_hash,revision)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS stage_access_audit(revision BIGINT UNSIGNED PRIMARY KEY,before_data MEDIUMBLOB NOT NULL,after_data MEDIUMBLOB NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS battle_settlements(serial INT UNSIGNED PRIMARY KEY,reports MEDIUMBLOB NOT NULL,result MEDIUMBLOB NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS accounts(
        uid BIGINT UNSIGNED PRIMARY KEY ,
        account VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE ,
        nickname VARCHAR(40) NOT NULL ,
        profile VARBINARY(360) NOT NULL ,
        salt VARBINARY(16) NOT NULL ,
        digest VARBINARY(32) NOT NULL ,
        legacy_salt VARBINARY(16) NOT NULL ,
        legacy_digest VARBINARY(32) NOT NULL ,
        gold BIGINT UNSIGNED NOT NULL DEFAULT 0 ,
        tickets BIGINT UNSIGNED NOT NULL DEFAULT 0
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS offers(
        catalog_key INT UNSIGNED PRIMARY KEY ,
        category TINYINT UNSIGNED NOT NULL ,
        variant TINYINT UNSIGNED NOT NULL ,
        record VARBINARY(108) NOT NULL ,
        grant_record VARBINARY(68) NOT NULL ,
        enabled BOOLEAN NOT NULL DEFAULT TRUE
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS item_definitions(definition_key INT UNSIGNED PRIMARY KEY,revision BIGINT UNSIGNED NOT NULL,record VARBINARY(68) NOT NULL,days INT UNSIGNED NOT NULL) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS counters(
        name VARCHAR(32) PRIMARY KEY ,
        value BIGINT UNSIGNED NOT NULL
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS training_claims(uid BIGINT UNSIGNED NOT NULL,operation_id VARCHAR(128) NOT NULL,started BIGINT NOT NULL,training_rank INT UNSIGNED NOT NULL,revision BIGINT UNSIGNED NOT NULL,experience INT UNSIGNED NOT NULL,PRIMARY KEY(uid,operation_id),UNIQUE KEY training_cycle(uid,started)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS vip_shop_rules(id TINYINT PRIMARY KEY,revision BIGINT UNSIGNED NOT NULL,rules MEDIUMBLOB NOT NULL) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS vip_shop_rules_audit(revision BIGINT UNSIGNED PRIMARY KEY,before_data MEDIUMBLOB NOT NULL,after_data MEDIUMBLOB NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS desktop_admin_operations(id VARCHAR(100) CHARACTER SET ascii PRIMARY KEY,request_hash BINARY(32) NOT NULL,before_data LONGBLOB NOT NULL,result_data LONGBLOB NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS stage_player_unlocks(uid BIGINT UNSIGNED NOT NULL,client_hash CHAR(64) CHARACTER SET ascii NOT NULL,revision BIGINT UNSIGNED NOT NULL,maps MEDIUMBLOB NOT NULL,PRIMARY KEY(uid,client_hash),FOREIGN KEY(uid) REFERENCES accounts(uid) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS friends(uid BIGINT UNSIGNED NOT NULL,friend_uid BIGINT UNSIGNED NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(uid,friend_uid),FOREIGN KEY(uid) REFERENCES accounts(uid) ON DELETE CASCADE,FOREIGN KEY(friend_uid) REFERENCES accounts(uid) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS character_creations(uid BIGINT UNSIGNED PRIMARY KEY,nickname VARCHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL UNIQUE,request VARBINARY(68) NOT NULL,FOREIGN KEY(uid) REFERENCES accounts(uid)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS talisman_uses(uid BIGINT UNSIGNED NOT NULL,operation_id VARCHAR(128) CHARACTER SET ascii NOT NULL,request BINARY(16) NOT NULL,PRIMARY KEY(uid,operation_id),FOREIGN KEY(uid) REFERENCES accounts(uid)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS talisman_repairs(uid BIGINT UNSIGNED NOT NULL,operation_id VARCHAR(128) CHARACTER SET ascii NOT NULL,instance INT UNSIGNED NOT NULL,material INT UNSIGNED NOT NULL,quantity INT UNSIGNED NOT NULL,capacity INT UNSIGNED NOT NULL,PRIMARY KEY(uid,operation_id),FOREIGN KEY(uid) REFERENCES accounts(uid)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS mailbox(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,uid BIGINT UNSIGNED NOT NULL,list_record VARBINARY(339) NOT NULL,detail_record VARBINARY(136) NOT NULL,is_read BOOLEAN NOT NULL DEFAULT FALSE,deleted BOOLEAN NOT NULL DEFAULT FALSE,claimed BOOLEAN NOT NULL DEFAULT FALSE,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX inbox(uid,deleted,id),FOREIGN KEY(uid) REFERENCES accounts(uid) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS gift_receipts(uid BIGINT UNSIGNED NOT NULL,operation_id VARCHAR(128) CHARACTER SET ascii NOT NULL,request_hash BINARY(32) NOT NULL,recipient BIGINT UNSIGNED NOT NULL,mail_id INT UNSIGNED NOT NULL,cost INT UNSIGNED NOT NULL,PRIMARY KEY(uid,operation_id),FOREIGN KEY(uid) REFERENCES accounts(uid)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS honour_stats(period INT UNSIGNED NOT NULL,uid BIGINT UNSIGNED NOT NULL,points BIGINT UNSIGNED NOT NULL,games BIGINT UNSIGNED NOT NULL,wins BIGINT UNSIGNED NOT NULL,PRIMARY KEY(period,uid),INDEX honour_rank(period,points),FOREIGN KEY(uid) REFERENCES accounts(uid) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS inventory(
        uid BIGINT UNSIGNED NOT NULL ,
        instance INT UNSIGNED NOT NULL ,
        record VARBINARY(68) NOT NULL ,
        PRIMARY KEY(uid ,
        instance) ,
        FOREIGN KEY(uid) REFERENCES accounts(uid)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS weapon_upgrades(uid BIGINT UNSIGNED NOT NULL,operation_id VARCHAR(128) CHARACTER SET ascii NOT NULL,instance INT UNSIGNED NOT NULL,success BOOLEAN NOT NULL,cost INT UNSIGNED NOT NULL,score_cost INT UNSIGNED NOT NULL,odds INT UNSIGNED NOT NULL,roll INT UNSIGNED NOT NULL,before_record VARBINARY(68) NOT NULL,after_record VARBINARY(68) NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(uid,operation_id),FOREIGN KEY(uid) REFERENCES accounts(uid)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS offer_lifetimes(catalog_key INT UNSIGNED PRIMARY KEY,days INT UNSIGNED NOT NULL,FOREIGN KEY(catalog_key) REFERENCES offers(catalog_key) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tutorial_rewards(uid BIGINT UNSIGNED PRIMARY KEY,reward MEDIUMBLOB NOT NULL,FOREIGN KEY(uid) REFERENCES accounts(uid) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS renewal_receipts(uid BIGINT UNSIGNED NOT NULL,operation_id VARCHAR(128) NOT NULL,request_hash BINARY(32) NOT NULL,instance INT UNSIGNED NOT NULL,PRIMARY KEY(uid,operation_id),FOREIGN KEY(uid) REFERENCES accounts(uid) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS level_reward_receipts(uid BIGINT UNSIGNED NOT NULL,level SMALLINT UNSIGNED NOT NULL,items MEDIUMBLOB NOT NULL,PRIMARY KEY(uid,level),FOREIGN KEY(uid) REFERENCES accounts(uid) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS purchases(
        uid BIGINT UNSIGNED NOT NULL ,
        operation_id VARCHAR(128) CHARACTER SET ascii NOT NULL ,
        request_hash BINARY(32) NOT NULL ,
        balance BIGINT UNSIGNED NOT NULL ,
        item_record VARBINARY(68) NOT NULL ,
        catalog_record VARBINARY(108) NOT NULL ,
        created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
        PRIMARY KEY(uid ,
        operation_id) ,
        FOREIGN KEY(uid) REFERENCES accounts(uid)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS wallet_operations(
        operation_id VARCHAR(128) CHARACTER SET ascii PRIMARY KEY ,
        uid BIGINT UNSIGNED NOT NULL ,
        mode VARCHAR(4) NOT NULL ,
        amount BIGINT UNSIGNED NOT NULL ,
        before_balance BIGINT UNSIGNED NOT NULL ,
        after_balance BIGINT UNSIGNED NOT NULL ,
        created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
        FOREIGN KEY(uid) REFERENCES accounts(uid)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS training_ranks(uid BIGINT UNSIGNED PRIMARY KEY,training_rank INT UNSIGNED NOT NULL DEFAULT 0,FOREIGN KEY(uid) REFERENCES accounts(uid) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS task_progress(uid BIGINT UNSIGNED NOT NULL,task_key SMALLINT UNSIGNED NOT NULL,state TINYINT UNSIGNED NOT NULL,baseline BINARY(116) NOT NULL,rule_revision BIGINT UNSIGNED NOT NULL,rule_data MEDIUMBLOB NULL,PRIMARY KEY(uid,task_key),FOREIGN KEY(uid) REFERENCES accounts(uid) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS extended_task_progress(uid BIGINT UNSIGNED NOT NULL,task_key SMALLINT UNSIGNED NOT NULL,cycle VARCHAR(10) NOT NULL,state TINYINT UNSIGNED NOT NULL,rule_revision BIGINT UNSIGNED NOT NULL,rule_data MEDIUMBLOB NOT NULL,counts BINARY(12) NOT NULL,PRIMARY KEY(uid,task_key,cycle),FOREIGN KEY(uid) REFERENCES accounts(uid) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS task_rewards(uid BIGINT UNSIGNED NOT NULL,task_key SMALLINT UNSIGNED NOT NULL,rule_revision BIGINT UNSIGNED NOT NULL,experience INT UNSIGNED NOT NULL,gold INT UNSIGNED NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(uid,task_key),FOREIGN KEY(uid) REFERENCES accounts(uid) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS title_rewards(uid BIGINT UNSIGNED NOT NULL,title_level TINYINT UNSIGNED NOT NULL,choices BLOB NOT NULL,claimed_key INT UNSIGNED NULL,claimed_instance INT UNSIGNED NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(uid,title_level),FOREIGN KEY(uid) REFERENCES accounts(uid) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS training(
        uid BIGINT UNSIGNED PRIMARY KEY ,
        started BIGINT NULL ,
        FOREIGN KEY(uid) REFERENCES accounts(uid)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS consumption_events (
	    uid BIGINT UNSIGNED NOT NULL,
	    battle INT UNSIGNED NOT NULL,
	    sequence INT UNSIGNED NOT NULL,
	    instance INT UNSIGNED NOT NULL,
	    signature VARBINARY(40) NOT NULL,
	    PRIMARY KEY(uid,battle,sequence),
	    FOREIGN KEY(uid) REFERENCES accounts(uid)
	) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS mail_attachments(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,mail_id INT UNSIGNED NOT NULL UNIQUE,uid BIGINT UNSIGNED NOT NULL,grant_record VARBINARY(68) NOT NULL,expiry_days INT UNSIGNED NOT NULL DEFAULT 0,claimed_instance INT UNSIGNED NULL,FOREIGN KEY(mail_id) REFERENCES mailbox(id) ON DELETE CASCADE,FOREIGN KEY(uid) REFERENCES accounts(uid) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS inventory_expirations(uid BIGINT UNSIGNED NOT NULL,instance INT UNSIGNED NOT NULL,expires_at BIGINT NOT NULL,processed BOOLEAN NOT NULL DEFAULT FALSE,PRIMARY KEY(uid,instance),INDEX due_inventory(uid,processed,expires_at),FOREIGN KEY(uid,instance) REFERENCES inventory(uid,instance) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS renewal_reminders(uid BIGINT UNSIGNED NOT NULL,instance INT UNSIGNED NOT NULL,ignored_deadline BIGINT NOT NULL,PRIMARY KEY(uid,instance),FOREIGN KEY(uid,instance) REFERENCES inventory(uid,instance) ON DELETE CASCADE) ENGINE=InnoDB;
